title: Ryo Sasaki Portfolio
markdown: kramdown

# for atom feed
author:
  name: Ryo Sasaki
  email: 33ki.job@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /works/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
